version: "3.9"
services:
  ms-purchase:
    container_name: ms-purchase
    image: devcoderjava/ms-purchase
    ports:
      - "4444:4444"
    networks:
      - spring
    restart: always

networks:
  spring:
    name: spring
