version: '3.9'

services:
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    networks:
      - spring
    environment:
      POSTGRES_PASSWORD: 1003
      POSTGRES_DB: db_realstate
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always #when start docker app, container postgres14 is created

volumes:
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring
