version: "3.9"
services:
  ms-real-state:
    container_name: ms-real-state
    image: devcoderjava/ms-real-state
    ports:
      - "3333:3333"
    networks:
      - spring
    restart: always

networks:
  spring:
    name: spring
